"use client";

import { ClientToServer, ServerToClient } from "./protocol";
import { eventBus } from "../utils/eventBus";
// @ts-ignore - This will be generated by build:proto
import { ntk } from "./proto/game";

/** Event types that must be buffered until GameApp flushes them. */
const BUFFERED_EVENT_TYPES = new Set<string>([
  "SpawnEntity",
  "SpawnCharacter",
  "EntityMove",
  "EntityRemove",
  "ChatNormal",
]);

export const entityNameCache = new Map<number, string>();

class GameSocket {
  private socket: WebSocket | null = null;
  private url: string = "ws://localhost:2010";
  private onMessageCallbacks: ((data: any) => void)[] = [];
  private onConnectionLostCallbacks: (() => void)[] = [];
  private onConnectCallbacks: (() => void)[] = [];

  /** The entity_id of the local player, set by LoginSuccess. */
  public localEntityId: number | null = null;

  /** Whether the WebSocket is currently open. */
  public connected: boolean = false;

  private retryCount = 0;
  private reconnectStartTime = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private readonly MAX_RETRIES = 10;
  private readonly MAX_RECONNECT_MS = 90_000;
  private readonly RETRY_DELAY_MS = 5_000;

  /** Buffer for game-critical events that arrive before GameApp has subscribed. */
  private eventBuffer: any[] = [];
  private bufferActive: boolean = true;

  connect() {
    if (this.socket && (this.socket.readyState === WebSocket.OPEN || this.socket.readyState === WebSocket.CONNECTING)) {
      console.log("Socket already open or connecting. Ababorting connect attempt.");
      return;
    }

    console.log(`Connecting to ${this.url}...`);

    if (this.reconnectStartTime === 0) {
      this.reconnectStartTime = Date.now();
    }

    this.socket = new WebSocket(this.url);
    this.socket.binaryType = "arraybuffer";

    this.socket.onopen = () => {
      console.log("Connected to server.");
      this.connected = true;
      this.retryCount = 0;
      this.reconnectStartTime = 0;
      this.onConnectCallbacks.forEach(cb => cb());
    };

    this.socket.onmessage = (event) => {
      try {
        if (event.data instanceof ArrayBuffer) {
          const uint8Array = new Uint8Array(event.data);
          const packet = ntk.GamePacket.decode(uint8Array);
          
          // The payload is inside the 'payload' oneof
          const payload = packet.payload;
          if (!payload) return;

          // Determine the type of payload and map it to the eventBus strings
          // Protobufjs uses camelCase for oneof fields
          let type = "";
          let data: any = null;

          if (payload.loginSuccess) {
            type = "LoginSuccess";
            data = payload.loginSuccess;
          } else if (payload.mapChange) {
            type = "MapChange";
            data = payload.mapChange;
          } else if (payload.spawnEntity) {
            type = "SpawnEntity";
            data = payload.spawnEntity;
          } else if (payload.spawnCharacter) {
            type = "SpawnCharacter";
            data = payload.spawnCharacter;
          } else if (payload.entityMove) {
            type = "EntityMove";
            data = payload.entityMove;
          } else if (payload.entityRemove) {
            type = "EntityRemove";
            data = payload.entityRemove;
          } else if (payload.playerPosition) {
            type = "PlayerPosition";
            data = payload.playerPosition;
          } else if (payload.playerVitalsUpdate) {
            type = "PlayerVitalsUpdate";
            data = payload.playerVitalsUpdate;
          } else if (payload.chatNormal) {
            type = "ChatNormal";
            data = payload.chatNormal;
          } else if (payload.systemMessage) {
            type = "SystemMessage";
            data = payload.systemMessage;
          } else if (payload.broadcastMessage) {
            type = "BroadcastMessage";
            data = payload.broadcastMessage;
          } else if (payload.dialogPopup) {
            type = "DialogPopup";
            data = payload.dialogPopup;
          } else if (payload.showMenu) {
            type = "ShowMenu";
            data = payload.showMenu;
          } else if (payload.inventoryUpdate) {
            type = "InventoryUpdate";
            data = payload.inventoryUpdate;
          } else if (payload.spellListUpdate) {
            type = "SpellListUpdate";
            data = payload.spellListUpdate;
          } else if (payload.playSound) {
            type = "PlaySound";
            data = payload.playSound;
          } else if (payload.playAnimation) {
            type = "PlayAnimation";
            data = payload.playAnimation;
          } else if (payload.damageNumber) {
            type = "DamageNumber";
            data = payload.damageNumber;
          }

          if (type) {
            // Log to debug console if available
            if ((window as any).addDebugLog) {
              (window as any).addDebugLog("in", type, uint8Array.length, data);
            }

            // Handle special logic for LoginSuccess
            if (type === "LoginSuccess") {
              this.localEntityId = Number(data.entityId);
            }

            // Handle special logic for MapChange (entity name caching)
            if (type === "MapChange" && data.objects) {
              data.objects.forEach((obj: any) => {
                if (obj.entityId && obj.name) {
                  entityNameCache.set(Number(obj.entityId), obj.name);
                }
              });
            }

            // Handle special logic for SpawnCharacter
            if (type === "SpawnCharacter") {
              entityNameCache.set(Number(data.entityId), data.name);
            }

            // Forward to EventBus
            this.forwardToEventBus(type, data);
            this.onMessageCallbacks.forEach(cb => cb({ type, payload: data }));
          }
        } else {
          // Fallback for legacy JSON (if any)
          const data = JSON.parse(event.data);
          this.forwardToEventBus(data.type, data.payload);
          this.onMessageCallbacks.forEach(cb => cb(data));
        }
      } catch (e) {
        console.error("Failed to decode Protobuf packet", e);
      }
    };

    this.socket.onclose = () => {
      console.log("Disconnected from server.");
      this.connected = false;
      this.localEntityId = null;
      this.onDisconnectCallbacks.forEach(cb => cb());
      this.scheduleReconnect();
    };

    this.socket.onerror = (error) => {
      console.error("WebSocket Error:", error);
    };
  }

  private forwardToEventBus(type: string, data: any) {
    // Map the decoded payload to the existing eventBus structure
    // Note: Protobufjs uses camelCase, so we might need to adjust if the eventBus expects snake_case
    // However, the existing code seems to handle both or expects specific keys.
    // We'll normalize the data to match what the eventBus/UI expects.

    const normalize = (obj: any) => {
      if (!obj || typeof obj !== 'object') return obj;
      const newObj: any = {};
      for (const key in obj) {
        // Convert camelCase to snake_case for compatibility with existing logic
        const snakeKey = key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
        newObj[snakeKey] = normalize(obj[key]);
      }
      return newObj;
    };

    const normalizedData = normalize(data);

    switch (type) {
      case "SpawnEntity":
        eventBus.emit("SpawnEntity", normalizedData);
        break;
      case "MapChange":
        eventBus.emit("MapTransitionStart", { map_id: normalizedData.map_id });
        eventBus.emit("MapChange", normalizedData);
        break;
      case "PlayerPosition":
        eventBus.emit("PlayerPosition", normalizedData);
        break;
      case "SpawnCharacter":
        eventBus.emit("SpawnCharacter", normalizedData);
        break;
      case "EntityMove":
        eventBus.emit("EntityMove", normalizedData);
        break;
      case "EntityRemove":
        eventBus.emit("EntityRemove", normalizedData);
        break;
      case "EntityHealthUpdate":
        eventBus.emit("EntityHealthUpdate", normalizedData);
        break;
      case "PlayerVitalsUpdate":
        eventBus.emit("PlayerVitalsUpdate", normalizedData);
        break;
      case "DialogPopup":
        eventBus.emit("DialogPopup", normalizedData);
        break;
      case "ShowMenu":
        eventBus.emit("ShowMenu", normalizedData);
        break;
      case "SystemMessage":
        eventBus.emit("SystemMessage", normalizedData);
        break;
      case "BroadcastMessage":
        eventBus.emit("BroadcastMessage", normalizedData);
        break;
      case "ChatNormal":
        eventBus.emit("ChatNormal", { ...normalizedData, entity_id: Number(normalizedData.entity_id) });
        break;
      case "InventoryUpdate":
        eventBus.emit("InventoryUpdate", normalizedData);
        break;
      case "SpellListUpdate":
        eventBus.emit("SpellListUpdate", normalizedData);
        break;
      case "PlaySound":
        eventBus.emit("PlaySound", normalizedData);
        break;
      case "PlayAnimation":
        eventBus.emit("PlayAnimation", normalizedData);
        break;
      case "DamageNumber":
        eventBus.emit("DamageNumber", normalizedData);
        break;
    }

    if (this.bufferActive && BUFFERED_EVENT_TYPES.has(type)) {
      this.eventBuffer.push({ type, payload: normalizedData });
    }
  }

  flushEventBuffer() {
    this.bufferActive = false;
    if (this.eventBuffer.length === 0) return;

    console.log(`[Socket] Flushing ${this.eventBuffer.length} buffered events to eventBus`);
    for (const packet of this.eventBuffer) {
      this.forwardToEventBus(packet.type, packet.payload);
    }
    this.eventBuffer = [];
  }

  send(packet: any) {
    if (this.socket && this.socket.readyState === WebSocket.OPEN) {
      try {
        // Wrap the payload in a GamePacket
        // We need to find the correct oneof field name in camelCase
        // e.g. { type: "LoginRequest", payload: { ... } } -> { loginRequest: { ... } }
        const oneofField = Object.keys(packet.payload)[0] || ""; // This is a bit hacky, assuming payload is the object
        
        // Actually, the user's protocol.ts defines ClientToServer as:
        // { type: K; payload: ClientMessages[K] }
        // We need to map 'LoginRequest' to 'loginRequest'
        const typeKey = packet.type.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase().replace(/_/g, '');
        // Wait, the oneof in proto is: login_request, login_success, etc.
        // Protobufjs converts snake_case to camelCase for the oneof fields.
        // So 'login_request' becomes 'loginRequest'.
        
        const protoPayload: any = {};
        const fieldName = packet.type.charAt(0).toLowerCase() + packet.type.slice(1);
        // If the type is 'LoginRequest', the field is 'loginRequest'
        // But we need to handle the snake_case to camelCase conversion correctly.
        // Let's use a more robust way to find the field name.
        
        // We'll try to find the field in the GamePacket definition
        // For simplicity, we'll assume the mapping is direct:
        // LoginRequest -> loginRequest
        // MoveRequest -> moveRequest
        // etc.
        
        const camelCaseType = packet.type
          .replace(/([a-z])([A-Z])/g, '$1$2') // This is not quite right for all cases
          .replace(/_([a-z])/g, (g) => g[1].toUpperCase()); // This is also not quite right

        // Let's just do a manual mapping for the known types to be safe
        const typeMap: Record<string, string> = {
          "LoginRequest": "loginRequest",
          "MoveRequest": "moveRequest",
          "ChatRequest": "chatRequest",
          "DialogResponse": "dialogResponse",
          "MenuResponse": "menuResponse",
          "UseItemRequest": "useItemRequest",
          "RequestDropItem": "requestDropItem",
          "CastSpell": "castSpell",
          "ActionRequest": "actionRequest", // if it exists
        };

        const field = typeMap[packet.type] || packet.type;

        const gamePacket = ntk.GamePacket.create({
          [field]: packet.payload
        });

        const encoded = ntk.GamePacket.encode(gamePacket).finish();
        
        if ((window as any).addDebugLog) {
          (window as any).addDebugLog("out", packet.type, encoded.length, packet.payload);
        }

        this.socket.send(encoded);
      } catch (e) {
        console.error("Failed to encode Protobuf packet", e);
      }
    } else {
      console.warn("Socket not open. Packet dropped:", packet.type);
    }
  }

  // ... rest of the class (reconnect logic, etc)
  private scheduleReconnect() {
    this.retryCount++;
    const elapsed = Date.now() - this.reconnectStartTime;

    if (this.retryCount > this.MAX_RETRIES || elapsed > this.MAX_RECONNECT_MS) {
      console.warn(
        `Giving up reconnection after ${this.retryCount} retries / ${Math.round(elapsed / 1000)}s`
      );
      this.resetRetryState();
      this.onConnectionLostCallbacks.forEach(cb => cb());
      return;
    }

    console.log(
      `Reconnect attempt ${this.retryCount}/${this.MAX_RETRIES} ` +
        `(${Math.round(elapsed / 1000)}s / ${this.MAX_RECONNECT_MS / 1000}s elapsed)`
    );
    this.reconnectTimer = setTimeout(() => this.connect(), this.RETRY_DELAY_MS);
  }

  private resetRetryState() {
    this.retryCount = 0;
    this.reconnectStartTime = 0;
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }

  onConnectionLost(callback: () => void) {
    this.onConnectionLostCallbacks.push(callback);
  }

  onConnect(callback: () => void) {
    this.onConnectCallbacks.push(callback);
  }

  onDisconnect(callback: () => void) {
    this.onDisconnectCallbacks.push(callback);
  }

  disconnect() {
    if (this.socket) {
      this.socket.onclose = null;
      this.socket.close();
      this.socket = null;
    }
    this.connected = false;
    this.localEntityId = null;
    this.bufferActive = true;
    this.eventBuffer = [];
  }
}

export const socket = new GameSocket();